after-login-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
exec-on-workspace-change = ["/bin/bash", "-c", "sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"]
after-startup-command = ["exec-and-forget sketchybar", "exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0"]

[key-mapping]
preset = "qwerty"

[gaps]
[gaps.inner]
horizontal = 12
vertical = 12

[gaps.outer]
left = 12
bottom = 12
top = 48
right = 12

[mode]
[mode.main.binding]
cmd-ctrl-alt-shift-w = ["mode workspace", "exec-and-forget echo WORKSPACE > $HOME/.aerospace.mode"]
cmd-ctrl-alt-shift-f = ["mode focus", "exec-and-forget echo FOCUS > $HOME/.aerospace.mode"]
cmd-ctrl-alt-shift-r = "reload-config"
cmd-ctrl-alt-shift-c = "exec-and-forget\n  padding=12\n  left=$(tomlq \".gaps.outer.left\" $HOME/.aerospace.toml)\n  if [ $left -eq 12 ]; then\n    screen_width=$(displayplacer list | grep -i resolution: | cut -d ' ' -f 2 | cut -d 'x' -f 1)\n    padding=$((screen_width / 5))\n  fi\n  tomlq -i -t \".gaps.outer.left=$padding\" $HOME/.aerospace.toml\n  tomlq -i -t \".gaps.outer.right=$padding\" $HOME/.aerospace.toml\n  aerospace reload-config\n"

[mode.focus.binding]
r = ["mode main", "reload-config", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
q = ["mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
x = ["close-all-windows-but-current", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
h = "focus left"
j = "focus down"
k = "focus up"
l = "focus right"
alt-h = "move left"
alt-j = "move down"
alt-k = "move up"
alt-l = "move right"
f = "fullscreen"
p = "layout floating tiling"

[mode.workspace.binding]
q = ["mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
tab = "workspace-back-and-forth"
l = "workspace next"
h = "workspace prev"
t = ["workspace T", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
b = ["workspace B", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
s = ["workspace S", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
o = ["workspace O", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
z = ["workspace Z", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
shift-t = ["move-node-to-workspace T", "workspace T", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
shift-b = ["move-node-to-workspace B", "workspace B", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
shift-s = ["move-node-to-workspace S", "workspace S", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
shift-o = ["move-node-to-workspace O", "workspace O", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
shift-z = ["move-node-to-workspace Z", "workspace Z", "mode main", "exec-and-forget echo MAIN > $HOME/.aerospace.mode"]
