[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#414b50"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#272e33"
foreground = "#d3c6aa"

[font]
size = 14

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Light"

[[keyboard.bindings]]
chars = "©"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "£"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "$"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "∞"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "§"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 26
mods = "Alt"

[[keyboard.bindings]]
chars = "~"
key = 30
mods = "Alt"

[[keyboard.bindings]]
chars = "¡"
key = "Key1"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "”"
key = "Key2"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "¥"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "$"
key = "Key4"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "‰"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "¶"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = '\'
key = "Key7"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "{"
key = "Key8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "}"
key = "Key9"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "≠"
key = "Key0"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "¿"
key = "Minus"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = """

"""
key = "J"
mods = "Control"

[schemes.everforest_dark_hard.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_hard.normal]
black = "#414b50"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_hard.primary]
background = "#272e33"
foreground = "#d3c6aa"

[schemes.sonokai.bright]
black = "0x7f8490"
blue = "0x76cce0"
cyan = "0xf39660"
green = "0x9ed072"
magenta = "0xb39df3"
red = "0xfc5d7c"
white = "0xe2e2e3"
yellow = "0xe7c664"

[schemes.sonokai.normal]
black = "0x252525"
blue = "0x76cce0"
cyan = "0xf39660"
green = "0x9ed072"
magenta = "0xb39df3"
red = "0xfc5d7c"
white = "0xe2e2e3"
yellow = "0xe7c664"

[schemes.sonokai.primary]
background = "0x27282C"
foreground = "0xe2e2e3"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/local/bin/fish"

[window]
decorations = "buttonless"

[window.padding]
x = 3
y = 3
