window:
  decorations: buttonless

  padding:
    x: 3
    y: 3

font:
  size: 14

  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Thin

colors:
  primary:
    background: "0x27282C"
    foreground: "0xe2e2e3"

  normal:
    black: "0x252525"
    red: "0xfc5d7c"
    green: "0x9ed072"
    yellow: "0xe7c664"
    blue: "0x76cce0"
    magenta: "0xb39df3"
    cyan: "0xf39660"
    white: "0xe2e2e3"

  bright:
    black: "0x7f8490"
    red: "0xfc5d7c"
    green: "0x9ed072"
    yellow: "0xe7c664"
    blue: "0x76cce0"
    magenta: "0xb39df3"
    cyan: "0xf39660"
    white: "0xe2e2e3"

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"

key_bindings:
  - { key: Key1,      mods: Alt,          chars: "\xA9"                  }
  - { key: Key2,      mods: Alt,          chars: "\x40"                  }
  - { key: Key3,      mods: Alt,          chars: "\xA3"                  }
  - { key: Key4,      mods: Alt,          chars: "\x24"                  }
  - { key: Key5,      mods: Alt,          chars: "∞"                     }
  - { key: Key6,      mods: Alt,          chars: "\xA7"                  }
  - { key: Key7,      mods: Alt,          chars: "\x7C"                  }
  - { key: Key8,      mods: Alt,          chars: "\x5B"                  }
  - { key: Key9,      mods: Alt,          chars: "\x5D"                  }
  - { key: Key0,      mods: Alt,          chars: "≈"                     }
  - { key: Minus,     mods: Alt,          chars: "\xB1"                  }
  - { key: 26, mods: Alt, chars: "|" }
  - { key: 26, mods: Shift|Alt, chars: "\\" }
  - { key: 30, mods: Alt, chars: "~" }
  - { key: 28, mods: Alt, chars: "[" }
  - { key: 25, mods: Alt, chars: "]" }
  - { key: 28, mods: Shift|Alt, chars: "{" }
  - { key: 25, mods: Shift|Alt, chars: "}" }
  
  - { key: Key1,      mods: Alt|Shift,    chars: "\xA1"                  }
  - { key: Key2,      mods: Alt|Shift,    chars: "”"                     }
  - { key: Key3,      mods: Alt|Shift,    chars: "\xA5"                  }
  - { key: Key4,      mods: Alt|Shift,    chars: "\x24"                  }
  - { key: Key5,      mods: Alt|Shift,    chars: "‰"                     }
  - { key: Key6,      mods: Alt|Shift,    chars: "\xB6"                  }
  - { key: Key7,      mods: Alt|Shift,    chars: "\x5C"                  }
  - { key: Key8,      mods: Alt|Shift,    chars: "\x7B"                  }
  - { key: Key9,      mods: Alt|Shift,    chars: "\x7D"                  }
  - { key: Key0,      mods: Alt|Shift,    chars: "≠"                     }
  - { key: Minus,     mods: Alt|Shift,    chars: "\xBF"                  }

# Replace the default bindings for these as the VirtualKeycodes don't match reality
  - { key: Minus,     mods: Command,      action: DecreaseFontSize       }
  - { key: Plus,      mods: Command,      action: IncreaseFontSize       }
  - { key: N,         mods: Control|Shift, action: CreateNewWindow }
  - { key: J,         mods: Control, chars: "\x0A" }
