name: Test Neovim Boot

on:
  push:
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:

jobs:
  test:
    name: Nvim test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Install Neovim
        run: |
          brew install nvim

      - name: Symlink dotfiles
        run: |
          BASE_PATH="$(git rev-parse --show-toplevel)"
          ln -s "$BASE_PATH/.config/nvim" "$HOME/.config/nvim"

      - name: Run Tests
        id: test
        run: |
          # Test for bootup errors
          # Simple way to see if some plugin update might break
          tmp_err_logs="$(mktemp)"

          # Sleep for 5 seconds to catch async errors
          nvim --headless "+:silent !sleep 5" +:qa! 2> "${tmp_err_logs}"

          if grep -q Error "${tmp_err_logs}"; then
            echo "Error encountered while booting nvim"
            echo "Error log:"
            cat "${tmp_err_logs}"
            exit 1
          fi
